In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_2017 = pd.read_csv ('table-6-2017-18.csv')
df_2017.head()

C:\Users\farab\AppData\Local\Temp\ipykernel_24752\3122574376.py:1: DtypeWarning: Columns (0,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017 = pd.read_csv ('table-6-2017-18.csv')

,Title,"Graduate activities by provider, country of provider, permanent address, level of qualification obtained, mode of former study, interim study and academic year",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Location,UK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Academic years,2017/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Data source,HESA / OfS / DfE(NI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sourced from,Detailed tables (Graduate Outcomes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Data source link,https://www.hesa.ac.uk/data-and-analysis/gradu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_2017 = pd.read_csv ('table-6-2017-18.csv', skiprows=8)
df_2017.head()

C:\Users\farab\AppData\Local\Temp\ipykernel_24752\2420214684.py:1: DtypeWarning: Columns (0,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017 = pd.read_csv ('table-6-2017-18.csv', skiprows=8)

,Code page,Unicode UTF-8,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Disclaimer,Please note that this data includes rounded to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Table 2017/18 total,769195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Last updated,Jun-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UKPRN,Provider name,Country of provider,Permanent address,Level of qualification obtained,Mode of former study,Interim study,Activity,Academic year,Number,Percent,95% confidence interval

In [4]:
df_2017 = pd.read_csv ('table-6-2017-18.csv', skiprows=13)
df_2017.head()

,UKPRN,Provider name,Country of provider,Permanent address,Level of qualification obtained,Mode of former study,Interim study,Activity,Academic year,Number,Percent,95% confidence interval
0,10008071.0,AA School of Architecture,All,All,All,All,Exclude significant interim study,Employment and further study,2017/18,15,12%,(6%-22%)
1,10008071.0,AA School of Architecture,All,All,All,All,Exclude significant interim study,Full-time employment,2017/18,90,67%,(55%-77%)
2,10008071.0,AA School of Architecture,All,All,All,All,Exclude significant interim study,Full-time further study,2017/18,0,1%,(0%-7%)
3,10008071.0,AA School of Architecture,All,All,All,All,Exclude significant interim study,Non-respondents,2017/18,85,NaN,NaN
4,10008071.0,AA School of Architecture,All,All,All,All,Exclude significant interim study,"Other including travel, caring for someone or ...",2017/18,5,2%,(1%-9%)

In [5]:
print(df_2017['Activity'].unique())

df_other_activities = df_2017[df_2017['Activity'] == 'Non-respondents']
df_other_activities.head()

['Employment and further study' 'Full-time employment'
 'Full-time further study' 'Non-respondents'
 'Other including travel, caring for someone or retired'
 'Part-time employment' 'Part-time further study' 'Total'
 'Total with known outcomes' 'Unemployed' 'Unknown pattern of employment'
 'Unknown pattern of further study' 'Voluntary or unpaid work']

,UKPRN,Provider name,Country of provider,Permanent address,Level of qualification obtained,Mode of former study,Interim study,Activity,Academic year,Number,Percent,95% confidence interval
3,10008071.0,AA School of Architecture,All,All,All,All,Exclude significant interim study,Non-respondents,2017/18,85,NaN,NaN
16,10008071.0,AA School of Architecture,All,All,All,All,Include significant interim study,Non-respondents,2017/18,85,NaN,NaN
29,10008071.0,AA School of Architecture,All,All,All,Full-time,Exclude significant interim study,Non-respondents,2017/18,85,NaN,NaN
42,10008071.0,AA School of Architecture,All,All,All,Full-time,Include significant interim study,Non-respondents,2017/18,85,NaN,NaN
55,10008071.0,AA School of Architecture,All,All,Postgraduate,All,Exclude significant interim study,Non-respondents,2017/18,60,NaN,NaN

In [ ]:
"""
EDA is Failure In this case because doesnt have correlation 
"""